version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-shop-1
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
